#! /bin/sh



########################################################################

_base=6
_minor=14
_release=1
_pkgver="$_base.$_minor"
wine_pkg="wine-$_pkgver"
staging_pkg="wine-staging-$_pkgver"
_basedir=$(dirname "$(readlink -f "$0")")
_srcdir="$_basedir/src"
_march="native" #name of the target architecture
_pkgdir="$_basedir/pkg/wine-ltsdw-$_pkgver.$_release"

########################################################################
#dxvk
########################################################################
_dxvk_base=1
_dxvk_minor=9
_dxvk_release=1
_dxvk_ver="$_dxvk_base.$_dxvk_minor.$_dxvk_release"
########################################################################


########################################################################
#gallium nine
########################################################################
_nine_base=0
_nine_minor=8
_nine_ver="$_nine_base.$_nine_minor"
########################################################################


########################################################################
_w32AppFont()
{
    #font aliasing settings for Win32 applications
    if ! [ -z $XDG_CONFIG_HOME ]; then
        font_dir_path="$XDG_CONFIG_HOME/fontconfig/conf.d"
        install -d "$font_dir_path"
        install -m644 "$_basedir/font/30-win32-aliases.conf" "$font_dir_path"
    fi
}

_w32AppFontDel()
{
    #delete font file for Win32 applications
    if ! [ -z "$XDG_CONFIG_HOME" ]; then
        font_dir_path="$XDG_CONFIG_HOME/fontconfig/conf.d"
        rm "$font_dir_path/30-win32-aliases.conf"
    fi
}

_installWinetricks()
{
    # download winetricks and put inside wine package
    curl -L "https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks" -o \
        "$_pkgdir/usr/bin/winetricks" -#

    chmod 755 "$_pkgdir/usr/bin/winetricks"
}

_installDXVK()
{
    _dxvk_dir="$_srcdir/dxvk/dxvk-$_dxvk_ver"

    # remove old files if exists 
    rm -rf "$_dxvk_dir"

    # download the specified version of dxvk
    curl -L "https://github.com/doitsujin/dxvk/releases/download/v$_dxvk_ver/dxvk-$_dxvk_ver.tar.gz" -o "$_basedir/dxvk.tar.gz" -#
    mkdir -p "$_srcdir/dxvk"
    tar xvf "$_basedir/dxvk.tar.gz" -C "$_srcdir/dxvk"

    # install the files to the specific architectures and make some pathing adjustment
    rm -rf "$_pkgdir/usr/lib/dxvk/x64"
    rm -rf "$_pkgdir/usr/lib32/dxvk/x32"
    install -D -m644 "$_dxvk_dir/x32/"*.dll -t "$_pkgdir/usr/lib32/dxvk/x32"
    install -D -m644 "$_dxvk_dir/x64/"*.dll -t "$_pkgdir/usr/lib/dxvk/x64"

    sed -i 's/dxvk_lib32=${dxvk_lib32:-"x32"}/dxvk_lib32=${dxvk_lib32:-"..\/lib32\/dxvk\/x32"}/' "$_dxvk_dir/setup_dxvk.sh"
    sed -i 's/dxvk_lib64=${dxvk_lib64:-"x64"}/dxvk_lib64=${dxvk_lib64:-"..\/lib\/dxvk\/x64"}/' "$_dxvk_dir/setup_dxvk.sh"
    install -m755 "$_srcdir/dxvk/dxvk-$_dxvk_ver/setup_dxvk.sh" -t "$_pkgdir/usr/bin/"
}

_installNine()
{
    _nine_dir="$_srcdir/gallium-nine/gallium-nine-standalone"

    # remove old files if exists 
    rm -rf "$_nine_dir"

    nine="gallium-nine-standalone.tar.gz"

    # download the specified version of gallium-nine-standalone
    curl -L "https://github.com/iXit/wine-nine-standalone/releases/download/v$_nine_ver/gallium-nine-standalone-v$_nine_ver.tar.gz" \
        -o "$_basedir/$nine" -#
    mkdir -p "$_srcdir/gallium-nine"
    tar xvf "$_basedir/$nine" -C "$_srcdir/gallium-nine"

    # install the files to the specific architectures and make some pathing adjustment
    install -D -m644 "$_nine_dir/bin32/ninewinecfg.exe.so" -t "$_pkgdir/usr/lib32/nine/x32"
    install -D -m644 "$_nine_dir/bin64/ninewinecfg.exe.so" -t "$_pkgdir/usr/lib/nine/x64"
    install -D -m644 "$_nine_dir/lib32/d3d9-nine.dll.so" -t "$_pkgdir/usr/lib32/nine/x32"
    install -D -m644 "$_nine_dir/lib64/d3d9-nine.dll.so" -t "$_pkgdir/usr/lib/nine/x64"

    sed -i 's/$BASE\/bin32/$BASE\/..\/lib32\/nine\/x32/g' "$_nine_dir/nine-install.sh"
    sed -i 's/$BASE\/bin64/$BASE\/..\/lib\/nine\/x64/g' "$_nine_dir/nine-install.sh"
    sed -i 's/$BASE\/lib32/$BASE\/..\/lib32\/nine\/x32/g' "$_nine_dir/nine-install.sh"
    sed -i 's/$BASE\/lib64/$BASE\/..\/lib\/nine\/x64/g' "$_nine_dir/nine-install.sh"

    install -m755 "$_nine_dir/nine-install.sh" -t "$_pkgdir/usr/bin"
}

_init()
{
    mkdir -p $_srcdir #create source directory if not exist

    t_winepkg="wine.tar.xz"
    t_stagingpkg="wine-staging.tar.gz"
    curl_wine="curl -L https://dl.winehq.org/wine/source/$_base.x/wine-$_pkgver.tar.xz -o $t_winepkg -#"
    curl_staging="curl -L https://github.com/wine-staging/wine-staging/archive/v$_pkgver/wine-staging-v$_pkgver.tar.gz -o $t_stagingpkg -#"

    if ! [ -f "$t_winepkg" ]; then
        echo "dowloading $t_winepkg"
        $curl_wine
    fi

    if ! [ -f "$t_stagingpkg" ]; then
        echo "downloading $t_stagingpkg"
        $curl_staging
    fi

    #excracting source
    tar xvf "$t_winepkg" -C "$_srcdir"
    tar xvf "$t_stagingpkg" -C "$_srcdir"
}

_srcClean()
{
    #delete all files and directory inside source directory
    echo "Cleaning src directory"
    rm -rf "$_srcdir/wine-"*
    rm -rf "$_srcdir/dxvk"
}

_autoConf()
{
    #build the server/trace.c and server/request.h files from the contents of server/protocol.def. 
    cd "$_srcdir/$wine_pkg"
    tools/make_requests
    autoreconf -f
    cd "$_basedir"
}

_prepare()
{
    cd $_srcdir

    #clean early build
    rm -rf $wine_pkg-32-build
    rm -rf $wine_pkg-64-build

    mkdir -p $wine_pkg-32-build
    mkdir -p $wine_pkg-64-build

    #patches to aply to wine-staging
    for patch in $_basedir/patches/staging/*; do
        if [ -f $patch ]; then
            echo "applying $patch"
            patch -d "$_srcdir/$staging_pkg" -p1 -i $patch
        fi
    done

    #staging patches
    "$_srcdir/$staging_pkg/patches/patchinstall.sh" DESTDIR="$_srcdir/$wine_pkg" --all --force-autoconf

    #patches to apply to wine
    for patch in $_basedir/patches/*; do
        if [ -f $patch ]; then
            echo "applying $patch"
            patch -d "$_srcdir/$wine_pkg" -p1 -i $patch
        fi
    done

    _autoConf

    #use generic processor architecture if not specified 
    if ! [ -z $_march ]; then
        export CFLAGS="-march=$_march -Ofast -fno-lto -falign-functions=32 -fno-math-errno -fno-semantic-interposition -fno-trapping-math"
        export CXXFLAGS="-march=$_march -Ofast -fno-flto -falign-functions=32 -fno-math-errno -fno-semantic-interposition -fno-trapping-math"
    else
        export CFLAGS="-march=x86-64 -mtune=generic -O2"
        export CXXFLAGS="-march=x86-64 -mtune=generic -O2"
    fi

    export LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"

    #build 64 bits
    cd "$_srcdir/$wine_pkg-64-build"
    ../$wine_pkg/configure \
        --prefix=/usr \
        --libdir=/usr/lib \
        --with-x \
        --with-gstreamer \
        --enable-win64 \
        --with-xattr

    make -j$(nproc)

    #build 32 bits
    export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
    cd "$_srcdir/$wine_pkg-32-build"
    ../$wine_pkg/configure \
        --prefix=/usr \
        --with-x \
        --with-gstreamer \
        --with-xattr \
        --libdir=/usr/lib32 \
        --with-wine64="$_srcdir/$wine_pkg-64-build"

    make -j$(nproc)
}

_package()
{
    cd "$_srcdir/$wine_pkg-32-build"
    make prefix="$_pkgdir/usr" \
        libdir="$_pkgdir/usr/lib32" \
        dlldir="$_pkgdir/usr/lib32/wine" install

    cd "$_srcdir/$wine_pkg-64-build"
    make prefix="$_pkgdir/usr" \
        libdir="$_pkgdir/usr/lib" \
        dlldir="$_pkgdir/usr/lib/wine" install

    echo "removing unneeded symbols, drasticaly reducing the size"
    i686-w64-mingw32-strip --strip-unneeded "$_pkgdir/usr/lib32/wine/i386-windows/"*.dll
    x86_64-w64-mingw32-strip --strip-unneeded "$_pkgdir/usr/lib/wine/x86_64-windows/"*.dll
}

case "$1" in
    install )
        _srcClean           && \
        _init               && \
        _prepare            && \
        _package            && \
        _installWinetricks  && \
        _installDXVK        && \
        _installNine        && \
        _w32AppFont;;
    *       )
        exit 1
esac
